def main():
    adj1=input('type an adjective')
    amount1=input('type an amount')
    adj2=input('type an adjective')
    verbing=input('type a verb with an -ing ending')
    noun1=input('type a noun')
    name1=input('type a name')
    phrase1=input('type a phrase')
    verb1=input('type a verb')
    noun2=input('type a noun')
    adj3=input('type an adjective')
    nouns1=input('type a plural noun')
    noun3=input('type an noun')
    phrase2=input('type a phrase')
    amount2=input('type an amount')
    name2=input('type a name')
    adjly1=input('type an adjective with an -ly ending')
    verbed1=input('type a verb with an -ed ending')
    verbed2=input('type a verb with an -ed ending')
    adj4=input('type an adjective')
    adj5=input('type an adjective')
    print('')
    print('')
    print("here'"'s your story...')
    print('my',adj1, "mother has",amount1, '''corgis.''')
    print('and they are very',adj2,".")
    print('One day she went',verbing," and she found a", noun1)
    print('Next to the',noun1," she found a man named",name1)
    print('He had red hair and a yellow dress and liked to',verb1)
    print('the man said"I miss my girlfriend," and',phrase1)
    print('I miss my husband, he died in the',noun2, "war.")
    print('they then told eachother',adj3," storys about",nouns1,'''.''')
    print('The corgis had made a',noun3," and where about to use it for the first time.")
    print('One said',phrase2, "while another said what?")
    print('then their creaton exploded into',amount2, "pieces.")
    print('then',name2, "walked by and stole all the corgis",adjly1,'''.''')
    print('the man',verbed1," the corgis and made them sadwiches.")
    print('the corgis',verbed2," and had a",adj4, """day.""")
    print('and no one ever saw them again. the',adj5," end.")
main()
